win32: build without threads but still with implicit sys
Discovered while trying to test #17601 since the build failed with:

perllib.c(62): error C2039: 'cur_tid': is not a member of 'interp_intern'
...\perl\win32\win32.h(566): note: see declaration of 'interp_intern'
perllib.c(68): error C2039: 'cur_tid': is not a member of 'interp_intern'
...\perl\win32\win32.h(566): note: see declaration of 'interp_intern'