ParseXS: simplify and test for dup arg handling.
ExtUtils::ParseXS had no tests for the

    Error: duplicate definition of argument 'foo'

error message.

This commit adds some tests, and also simplifies the duplicate-detecting
code. A redundant check was causing the error to be printed *twice* for
the same parameter in something like:

    void foo(int a)
        int a

Removing this redundancy also allows the removal of the now-unused
$self->{xsub_map_argname_to_seen_type} object field.