Revert "make PerlIO handle FD_CLOEXEC"
This reverts commit 2cdf406af42834c46ef407517daab0734f7066fc.

The reason for the revert is that with this commit, perl fails to
compile on darwin (or at least, one some versions of it):

    ./miniperl -Ilib make_ext.pl lib/auto/DB_File/DB_File.bundle  MAKE="/Applications/Xcode.app/Contents/Developer/usr/bin/make" LIBPERL_A=libperl.a LINKTYPE=dynamic
    Parsing config.in...
    Looks Good.
    dyld: lazy symbol binding failed: Symbol not found: _mkostemp
      Referenced from: /private/tmp/perl/cpan/DB_File/../../miniperl
      Expected in: flat namespace

    dyld: Symbol not found: _mkostemp
      Referenced from: /private/tmp/perl/cpan/DB_File/../../miniperl
      Expected in: flat namespace

    Unsuccessful Makefile.PL(cpan/DB_File): code=5 at make_ext.pl line 518.
    make: *** [lib/auto/DB_File/DB_File.bundle] Error 2