WIP new more efficient mem allocator for threaded Win32 Perlu
-Previously a linked list was used, so individual threads and psuedoforks
 could wipe out their memory, even if perl's or random XS code's poor
 design leaked it. The PMEMORY_BLOCK_HEADER was 3 pointers big, every mem
 block had to have this 3 pointer big header on it. It adds up. While
 malloc is global to the process (egh, specifically the particular CRT),
 the malloc in all CRTs on Win2K and newer use HeapAlloc internally by
 default, not the Dos Windows CRT "small-block heap". So instead of cutting
 up malloc into pools, just create our own pools, the way the per-CRT
 malloc does. Threaded Win32 Perl has had "Free to wrong pool" checking
 since day 1 of threads. Even in the 2010s, random XS devs still trip
 this occasionally, so I dont think the error checking can be removed at
 this point. This commit reduces the header from 3 pointers big, to 1
 pointer big, a savings of 8 or 16 bytes per mem alloc. Also this commit
 removed a CS aquire/release pair for every memory function (HeapAlloc
 contains its own CS internally).

XXXX Add new heap for XP 2K flag SetHeapInformation thing, partial done

XXXX look at machine code of heap APIs that return BOOL, decide if they
return false instead of throw exceptions even tho we asked for exceptions
right now retvals are not checked, any point of even doing anything about
a failed HeapDestroy?

XXXX add tests to XS APITest for bad newx behavior, add tests for Free to
wrong pool, where to capture SEH (check self expanding stack patch)?
or only on VC perl? GCC perl gets no HEAP_GENERATE_EXCEPTIONS flag?

XXXX combine MemShared and MemParse VMem instances?

XXXX split VMem into refcnted and non refcnted class so per perl Mem obj
is not refcounted, only shared is?

-Add ReleaseVoid, since void Release(void) and long Release(void) in the
 same class are illegal in C++ (error C2556). ReleaseVoid avoids saving the new refcount
 to return it later, around a function class. This removes instructions to
 save and restore nonvol registers. "long Release(void)" is optimized out
 of the perl523.dll binary by CC/LD.