util.c - move was_here to be initialized earlier
Otherwise the goto out_of_memory breaks threaded builds under debugging
as originally reported by Karl as we jump over the initialization
of the variable and then use it later on.

    util.c: In function ‘void* Perl_safesysrealloc(void*, size_t)’:
    util.c:335:11: error: jump to label ‘out_of_memory’
      335 |           out_of_memory:
          |           ^~~~~~~~~~~~~
    util.c:248:18: note:   from here
      248 |             goto out_of_memory;
          |                  ^~~~~~~~~~~~~
    util.c:277:12: note:   crosses initialization of ‘UV was_where’
      277 |         UV was_where = PTR2UV(where);
          |            ^~~~~~~~~
    make: *** [makefile:260: util.o] Error 1