CUSTOMIZED entry needs relative path from distribution
Per Porting/Maintainers.pl, "The path [to an entry in the CUSTOMIZED
element of a particular module's entry in %MODULES] should be relative
to the distribution directory."  In this case, the distribution
directory is 'cpan/Filter-Util/', so we have to go up two levels in
order to position ourselves to see 'pod/perlfilter.pod'.

If not corrected, when running 'perl Porting/sync-with-cpan
Filter::Util::Call', we get this message:

        error: pathspec 'Filter-Util-Call/pod/perlfilter.pod'
        did not match any file(s) known to git"

Not surprisingly, we also get a failure in 't/porting/customized.t' if
we don't correct this.