ParseXS: detect OUTPUT: SETMAGIC: bad arg values
Previously a bad OUTPUT line like this:

    OUTPUT:
        SETMAGIC: 1

emitted a generic and confusing warning message:

    Error: OUTPUT SETMAGIC: not a parameter

because a SETMAGIC line which wasn't syntactically correct was parsed
as a general OUTPUT: line.

This commit instead treats it as a SETMAGIC line, but with an invalid
argument, and adds a suitable new error message:

    Error: SETMAGIC: invalid value '1' (should be ENABLE/DISABLE)