VMem refactor part 1+Parse mem pool removal
-Add ReleaseVoid, since void Release(void) and long Release(void) in the
 same class are illegal in C++ (error C2556). ReleaseVoid avoids saving the new refcount
 to return it later, around a function class. This removes instructions to
 save and restore nonvol registers. "long Release(void)" is optimized out
 of the perl523.dll binary by CC/LD.
-Remove "Parse" memory pool, it seems to have never been used since it was
 introduced in commit 7766f1371a in 5.00563, removing "Parse" removes
 vtables, C++ obj members, func args, machine code, runtime memory, etc
 associated with the Parse memory pool. NewWare is untestable by me.
-Add a test that "free to wrong pool" doesn't accidentally stop working.
 Future refactoring of VMem class might cause "free to wrong pool" to
 accidentally stop catching thread mixups.
-dont aquire the VMem lock twice (call EnterCriticalSection twice) if
 using _USE_MSVCRT_MEM_ALLOC, the other allocator at the bottom has no
 serialization, and therefore _USE_MSVCRT_MEM_ALLOC doesn't need it either
 while I could narrow the scope of the locks in VMem methods and remove
 the locks in CPerlHost if using _USE_MSVCRT_MEM_ALLOC, I decided against
 it since most mallocs are per-interp/per-thread, shared memory is only for
 sub optrees and hint hashes and etc, and it is rare to compile/load perl
 code compared to running perl opcode code. With removal of the locks in
 VMem the caller (PerlMemSharedMalloc) must serialize if needed, and for
 PerlMem no locks at all are needed. This supports spliting VMem into a
 shared and non-shared class in the next commit.
-remove the 2nd "FreeLock()"/LeaveCriticalSection branch in ::Malloc,
 ::Realloc, and ::Free, remove "ptr = NULL;"/load zero instruction and
 just pass through the NULL from CRT alloc
-rearrange the code for "Free to wrong pool" so nowhere is a cheap vol reg
 and that NULL isn't saved across a function call
-add NOT_REACHED since there is no recovery from a SEGV, and remove a
 scenario where no warning would be printed on a double free, if the
 memblock was not overwritten/handed back out by the time of the 2nd free()
 and kept its owner member as NULL

Size of VC2013 32b perl523.dll's .text section before, 0xE182B bytes of
machine code, after 0xE1625 bytes.