locale.c: Fix trial_locales declaration (fix g++)
Commit e57aaf750b3d2461053eff690d0954bc8fb9d7f3 broke builds with g++
because the declaration of `trial_locales` was incorrect. It contained
an extra 'struct' keyword which is wrong.

Errors on g++:
	locale.c:3539:12: error: using typedef-name 'trial_locales_struct' after 'struct'
	     struct trial_locales_struct trial_locales[5];
            ^
	locale.c:3537:7: note: 'trial_locales_struct' has a previous declaration here
	     } trial_locales_struct;

(Build tested with gcc-12, g++-12, gcc-4.9, g++-4.9)