Fixes typo from d223e1ea9ae864c0e563187f1e76240ef1acad87
This breaks in malloc.c when configured using the Perl malloc implementation i.e. -Dusemymalloc

End result is this when linking:

    /usr/bin/ld: malloc.o: in function `Perl_mfree':
    malloc.c:(.text+0x98): undefined reference to `nBITMASK'
    /usr/bin/ld: malloc.c:(.text+0xb9): undefined reference to `nBITMASK'
    /usr/bin/ld: malloc.c:(.text+0xd3): undefined reference to `nBITMASK'
    /usr/bin/ld: malloc.c:(.text+0x138): undefined reference to `nBITMASK'
    /usr/bin/ld: malloc.o: in function `Perl_malloced_size':
    malloc.c:(.text+0x1fc): undefined reference to `nBITMASK'
    /usr/bin/ld: malloc.o:malloc.c:(.text+0x328): more undefined references to `nBITMASK' follow