Revert "tweak NOT_REACHED in DEBUGGING builds"
This reverts commit 5b48e25f83f62f48ea280c49b00302e063384348.

The above commit breaks win32 builds:

    IO.xs(73) : error C2065: 'my_perl' : undeclared identifier
    IO.xs(73) : error C2223: left of '->IProc' must point to struct/union

where dist/IO/IO.xs contains:

    69: static int
    70: not_here(const char *s)
    71: {
    72:     croak("%s not implemented on this architecture", s);
    73:     NORETURN_FUNCTION_END;
    74: }

and perl.h contains:

    #  define NORETURN_FUNCTION_END NOT_REACHED;