Fix compilation of -DPERL_MEM_LOG
This no longer compiled, giving the error

locale.c:2878:15: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]

The simple solution is to change memlog to explicitly have a const
parameter.