testsuite.yml: use windows-2022 for MSVC
I've been seeing occasional MSVC run failures with the message:

The system cannot find the path specified.
'nmake' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 1.

from the build, and a notice:

NOTICE: windows-2025 requests are being redirected to
windows-2025-vs2026 by May 12, 2026

So use windows-2022, as suggested in runner-images/issues/14017 at
least until 5.45 opens up.

This has been reported elsewhere:

https://github.com/actions/runner-images/issues/14004

According to:

https://github.com/actions/runner-images/issues/14017

"During this period your workflows will gradually switch over to the
new image with Visual Studio 2026 as the default."

so we can expect this change to gradually become visible to all users
over the coming weeks.

Example failures:

https://github.com/tonycoz/perl5/actions/runs/25704574120/job/75472975842
https://github.com/tonycoz/perl5/actions/runs/25702895051/job/75467985059